[project]
name = "joml"
version = "0.2.0"
description = "A markup language for describing journeys"
readme = "README.md"
authors = [
    { name = "Thomas Leese", email = "thomas@leese.io" }
]
requires-python = ">=3.14"
dependencies = []

[build-system]
requires = ["uv_build>=0.12.21,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
    "pytest-cov>=7.1.0",
    "ruff>=0.16.10",
    "sphinx>=9.1.0",
    "ty>=0.0.84",
]
